{{- $deploymentMode := .Values.alloy.deploymentMode | default "alloy" }}
{{- if eq $deploymentMode "direct" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "redpanda-o11y.alloyResourceName" . }}-alloy
  namespace: {{ .Values.alloy.namespace }}
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: {{ .Values.alloy.name }}
    app.kubernetes.io/component: rbac
{{- end }}
