{{- $deploymentMode := .Values.alloy.deploymentMode | default "alloy" }}
{{- if eq $deploymentMode "direct" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "redpanda-o11y.alloyResourceName" . }}-alloy
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: {{ .Values.alloy.name }}
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "redpanda-o11y.alloyResourceName" . }}-alloy
subjects:
  - kind: ServiceAccount
    name: {{ include "redpanda-o11y.alloyResourceName" . }}-alloy
    namespace: {{ .Values.alloy.namespace }}
{{- end }}
